/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package musiczone;

import java.io.*;
import java.util.*;
import javax.swing.*;
import jaco.mp3.player.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.filechooser.*;

/**
 *
 * @author pnevmalex
 */
public class MusicZone extends javax.swing.JFrame {

    private ArrayList<File> playList = new ArrayList<File>();
    private MP3Player myplayer = new MP3Player();
    private MP3Player tempPlayer = new MP3Player();
    private int stopFlag;

    private File[] selectFiles() {
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Choose Your Songs");
        fc.setApproveButtonText("Add");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("MP3 Files", "mp3");
        fc.setFileFilter(filter);
        fc.setMultiSelectionEnabled(true);
        int fileIsValid = fc.showOpenDialog(this);
        if (fileIsValid == JFileChooser.APPROVE_OPTION) {
            return fc.getSelectedFiles();
        } else {
            return null;
        }
    }

    private void addToPlayList(File[] songs) {
        if (songs != null) {
            playList.addAll(Arrays.asList(songs));
            for (int i = 0; i < songs.length; i++) {
                if (songs[i] != null) {
                    myplayer.addToPlayList(songs[i]);
                }
            }
        }
    }

    private void deleteFromPlayList(int songIndex) {

        playList.remove(songIndex);
        myplayer.getPlayList().remove(songIndex);

    }

    private File getSongFromPlayList(int songIndex) {
        return playList.get(songIndex);
    }

    private void updateSongList() {
        String[] songNames = new String[playList.size()];
        for (int i = 0; i < playList.size(); i++) {
            songNames[i] = playList.get(i).getName();
        }
        songList.setListData(songNames);
        printMP3PlayList();
    }

    private void printMP3PlayList() {
        System.out.println(myplayer.getPlayList());
    }

    private void playSong() {
        if (songList.getSelectedIndex() == -1) {
            myplayer.stop();
            myplayer.play();
        } else {
            if (!myplayer.isPaused()) {
                myplayer.stop();
                if (!tempPlayer.getPlayList().isEmpty()) {
                    tempPlayer.getPlayList().remove(0);
                }
                tempPlayer.addToPlayList(getSongFromPlayList(songList.getSelectedIndex()));
                tempPlayer.play();
            }
            if (!tempPlayer.isPaused()) {
                tempPlayer.stop();
                if (!tempPlayer.getPlayList().isEmpty()) {
                    tempPlayer.getPlayList().remove(0);
                }
                tempPlayer.addToPlayList(getSongFromPlayList(songList.getSelectedIndex()));
                tempPlayer.play();
            }
        }
    }
           int delay = 500; //milliseconds
        ActionListener taskPerformer = new ActionListener() {
            
            @Override
            
            public void actionPerformed(ActionEvent evt) {
                if(tempPlayer.isStopped() && (stopFlag == 0)){
                    if (!tempPlayer.getPlayList().isEmpty()) {
                        if (songList.getSelectedIndex() == playList.size() - 1) {
                            songList.setSelectedIndex(0);
                            playSong();
                        } else {
                            int songIndex = songList.getSelectedIndex() + 1;
                            songList.setSelectedIndex(songIndex);
                            playSong();
                        }
                    }
                }
            }
        };

    /**
     * Creates new form MusicZone
     */
    public MusicZone() {
        initComponents();
        new javax.swing.Timer(delay,taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        mainpanel = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        onoma2 = new javax.swing.JLabel();
        grbtn = new javax.swing.JButton();
        usbtn = new javax.swing.JButton();
        about = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        songList = new javax.swing.JList<>();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        play = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        next = new javax.swing.JButton();
        repeat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MusicZone");
        setBackground(new java.awt.Color(30, 30, 30));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setPreferredSize(new java.awt.Dimension(800, 450));

        mainpanel.setBackground(new java.awt.Color(30, 30, 30));
        mainpanel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        mainpanel.setPreferredSize(new java.awt.Dimension(800, 500));

        sidepanel.setBackground(new java.awt.Color(5, 5, 5));

        title.setBackground(new java.awt.Color(5, 5, 5));
        title.setFont(new java.awt.Font("Cookie", 3, 45)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mainlogo.png"))); // NOI18N

        onoma2.setBackground(new java.awt.Color(5, 5, 5));
        onoma2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        onoma2.setForeground(new java.awt.Color(255, 255, 255));
        onoma2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        onoma2.setText("Αλέξανδρος Πνευμονίδης");
        onoma2.setToolTipText("it185263");

        grbtn.setBackground(new java.awt.Color(0, 0, 0));
        grbtn.setForeground(new java.awt.Color(255, 255, 255));
        grbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gr.png"))); // NOI18N
        grbtn.setToolTipText("Greek/Ελληνικά");
        grbtn.setBorder(null);
        grbtn.setBorderPainted(false);
        grbtn.setFocusable(false);
        grbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grbtnActionPerformed(evt);
            }
        });

        usbtn.setBackground(new java.awt.Color(0, 0, 0));
        usbtn.setForeground(new java.awt.Color(255, 255, 255));
        usbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/us.png"))); // NOI18N
        usbtn.setToolTipText("English/Αγγλικά");
        usbtn.setBorder(null);
        usbtn.setBorderPainted(false);
        usbtn.setFocusable(false);
        usbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usbtnActionPerformed(evt);
            }
        });

        about.setBackground(new java.awt.Color(5, 5, 5));
        about.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        about.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(about, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sidepanelLayout.createSequentialGroup()
                                .addComponent(grbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(onoma2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(about, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(onoma2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        songList.setBackground(new java.awt.Color(30, 30, 30));
        songList.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        songList.setForeground(new java.awt.Color(255, 255, 255));
        songList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        songList.setFocusable(false);
        songList.setSelectionBackground(new java.awt.Color(105, 105, 105));
        jScrollPane2.setViewportView(songList);

        add.setBackground(new java.awt.Color(30, 30, 30));
        add.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add Song");
        add.setFocusable(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(30, 30, 30));
        delete.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete Song");
        delete.setFocusable(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        play.setBackground(new java.awt.Color(30, 30, 30));
        play.setFont(new java.awt.Font("FreeSans", 0, 13)); // NOI18N
        play.setForeground(new java.awt.Color(255, 255, 255));
        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/play_btn.png"))); // NOI18N
        play.setFocusable(false);
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        stop.setBackground(new java.awt.Color(30, 30, 30));
        stop.setFont(new java.awt.Font("FreeSans", 0, 13)); // NOI18N
        stop.setForeground(new java.awt.Color(255, 255, 255));
        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/stop_btn.png"))); // NOI18N
        stop.setFocusable(false);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        previous.setBackground(new java.awt.Color(30, 30, 30));
        previous.setFont(new java.awt.Font("FreeSans", 0, 13)); // NOI18N
        previous.setForeground(new java.awt.Color(255, 255, 255));
        previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/prev.png"))); // NOI18N
        previous.setFocusable(false);
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        next.setBackground(new java.awt.Color(30, 30, 30));
        next.setFont(new java.awt.Font("FreeSans", 0, 13)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/next.png"))); // NOI18N
        next.setFocusable(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        repeat.setBackground(new java.awt.Color(30, 30, 30));
        repeat.setFont(new java.awt.Font("FreeSans", 0, 13)); // NOI18N
        repeat.setForeground(new java.awt.Color(255, 255, 255));
        repeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/notRepeat.png"))); // NOI18N
        repeat.setFocusable(false);
        repeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainpanelLayout.createSequentialGroup()
                            .addComponent(add)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete)))
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(repeat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(previous, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(play, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(repeat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        File[] songs = selectFiles();
        addToPlayList(songs);
        updateSongList();
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (songList.getSelectedIndex() >= 0) {
            int songIndex = songList.getSelectedIndex();
            deleteFromPlayList(songIndex);
            updateSongList();
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        if (songList.getSelectedIndex() >= 0){
            playSong();
        }
    }//GEN-LAST:event_playActionPerformed

    private void grbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grbtnActionPerformed
        about.setText("<html>Το MusicZone είναι ένα MP3 Player το οποίο δημιουργήθηκε από έναν φοιτητή του τμήματος Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων στα πλαίσια του μαθήματος Αλληλεπίδραση Ανθρώπου-Μηχανής του Διεθνούς Πανεπιστημίου Ελλάδας.</html>");
        add.setText("Προσθήκη");
        delete.setText("Διαγραφή");
    }//GEN-LAST:event_grbtnActionPerformed

    private void usbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usbtnActionPerformed
        about.setText("<html>MusicZone is an MP3 Player created by student of the Department of Computer Engineering and Electronic Systems in the course Human-Machine Interaction of the International Hellenic University.</html>");
        add.setText("Add Song");
        delete.setText("Delete Song");
    }//GEN-LAST:event_usbtnActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        if (!tempPlayer.isStopped()) {
            tempPlayer.stop();
            stopFlag = 1;
        }
    }//GEN-LAST:event_stopActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        if (songList.getSelectedIndex() >= 0) {
            if (songList.getSelectedIndex() == 0) {
                songList.setSelectedIndex(playList.size() - 1);
                playSong();
            } else {
                int songIndex = songList.getSelectedIndex() - 1;
                songList.setSelectedIndex(songIndex);
                playSong();
            }
        }
    }//GEN-LAST:event_previousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if (songList.getSelectedIndex() >= 0) {
            if (songList.getSelectedIndex() == playList.size() - 1) {
                songList.setSelectedIndex(0);
                playSong();
            } else {
                int songIndex = songList.getSelectedIndex() + 1;
                songList.setSelectedIndex(songIndex);
                playSong();
            }
        }
    }//GEN-LAST:event_nextActionPerformed

    private void repeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatActionPerformed
        if (songList.getSelectedIndex() >= 0) {
            if (tempPlayer.isRepeat() == false) {
                tempPlayer.setRepeat(true);
                repeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/repeat.png")));
            } else {
                tempPlayer.setRepeat(false);
                repeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/notRepeat.png")));
            }
        }
    }//GEN-LAST:event_repeatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicZone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicZone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicZone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicZone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicZone().setVisible(true);
                //app icon
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JButton add;
    private javax.swing.JPanel background;
    private javax.swing.JButton delete;
    private javax.swing.JButton grbtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JButton next;
    private javax.swing.JLabel onoma2;
    private javax.swing.JButton play;
    private javax.swing.JButton previous;
    private javax.swing.JButton repeat;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JList<String> songList;
    private javax.swing.JButton stop;
    private javax.swing.JLabel title;
    private javax.swing.JButton usbtn;
    // End of variables declaration//GEN-END:variables
}
